apiVersion: v1
kind: Service
metadata:
  name: {{ include "memo.fullname" . }}
  labels:
    {{- include "memo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "memo.selectorLabels" . | nindent 4 }}
