apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "memo.fullname" . }}
  labels:
    {{- include "memo.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "memo.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "memo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "memo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: main
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: {{ .Values.persistence.name }}
          mountPath: {{ .Values.persistence.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.name }}
    spec:
      accessModes: [ "{{ .Values.persistence.accessMode }}" ]
      storageClassName: {{ .Values.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}