---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: memo
  namespace: default
spec:
  selector:
    app: memo
  type: NodePort
  ports:
  - name: memo
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
---